name: build and deploy firefox extension to addons.mozilla.org

on:
  push:
    paths:
      - manifest.json
  workflow_dispatch:

jobs:
  render-manifests:
    name: Build extension and publish
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ./firefox-container

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true

      - name: Build the package
        run: |
          cd firefox-container
          nix run .#package

      - run:
          echo version=$(jq -r .version firefox-container/manifest.json) >> $GITHUB_ENV

      - name: Create release
        uses: ncipollo/release-action@v1.16.0
        with:
          artifacts: './firefox-container/web-ext-artifacts/heywoodlh_container-*.zip'
          tag: "${{ env.version }}"
          skipIfReleaseExists: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: heywoodlh-container
          xpi-path: firefox-container/web-ext-artifacts/heywoodlh_container-*.zip
          self-hosted: false
          jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
          jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}
          license: "MPL-2.0"

